// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Momo(props) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF("/3D_models/beasts/443815.glb");
  //const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature003"
          position={[-0.94, 0.08, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.23}
        >
          <primitive object={nodes.Bone_4} />
          <primitive object={nodes.Bone003_2} />
          <primitive object={nodes.Bone005_2} />
          <skinnedMesh
            name="Sphere013"
            geometry={nodes.Sphere013.geometry}
            material={nodes.Sphere013.material}
            skeleton={nodes.Sphere013.skeleton}
          />
        </group>
        <group
          name="Armature002"
          position={[-0.96, 0.96, 0]}
          rotation={[0, -Math.PI / 2, 0]}
          scale={0.19}
        >
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone003} />
          <primitive object={nodes.Bone005} />
          <skinnedMesh
            name="Sphere005"
            geometry={nodes.Sphere005.geometry}
            material={nodes.Sphere005.material}
            skeleton={nodes.Sphere005.skeleton}
          />
        </group>
        <group
          name="Armature137"
          position={[-1.31, 2.54, -32.76]}
          rotation={[1.2, -1.21, 1.33]}
          scale={0.4}
        >
          <primitive object={nodes.Bone_3} />
          <primitive object={nodes.Bone003_1} />
          <primitive object={nodes.Bone005_1} />
          <skinnedMesh
            name="Sphere058"
            geometry={nodes.Sphere058.geometry}
            material={materials["46.030"]}
            skeleton={nodes.Sphere058.skeleton}
          />
        </group>
        <group
          name="Armature001"
          position={[0, 1.5, 0]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.15}
        >
          <primitive object={nodes.Bone_5} />
          <skinnedMesh
            name="Cylinder001"
            geometry={nodes.Cylinder001.geometry}
            material={nodes.Cylinder001.material}
            skeleton={nodes.Cylinder001.skeleton}
          />
        </group>
        <group name="Armature004" position={[0, 1.5, 0]} scale={0.15}>
          <primitive object={nodes.Bone_6} />
          <skinnedMesh
            name="Cylinder002"
            geometry={nodes.Cylinder002.geometry}
            material={nodes.Cylinder002.material}
            skeleton={nodes.Cylinder002.skeleton}
          />
        </group>
        <mesh
          name="Cube"
          castShadow
          receiveShadow
          geometry={nodes.Cube.geometry}
          material={nodes.Cube.material}
          position={[0, 0.32, 0.13]}
          rotation={[0.38, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="Roundcube009"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube009.geometry}
          material={nodes.Roundcube009.material}
          position={[-0.94, 0.44, 0.22]}
          rotation={[0.28, 0.05, -0.05]}
          scale={[0.03, 0.03, 0.03]}
        />
        <mesh
          name="Cube002"
          castShadow
          receiveShadow
          geometry={nodes.Cube002.geometry}
          material={nodes.Cube002.material}
          position={[-0.95, 0.35, 0.16]}
          rotation={[0.38, 0, 0]}
          scale={[0.01, 0.01, 0.01]}
        />
        <mesh
          name="Roundcube621"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube621.geometry}
          material={nodes.Roundcube621.material}
          position={[0, 0.17, 0]}
          scale={0.11}
        >
          <mesh
            name="Roundcube619"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube619.geometry}
            material={nodes.Roundcube619.material}
            position={[0, 2.4, 0]}
            scale={1.72}
          />
          <mesh
            name="Roundcube620"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube620.geometry}
            material={nodes.Roundcube620.material}
            position={[0, 2.2, 1.67]}
            rotation={[-0.08, 0, 0]}
            scale={[0.37, 0.67, 0.37]}
          />
          <mesh
            name="Roundcube622"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube622.geometry}
            material={nodes.Roundcube622.material}
            position={[0, -1.22, 0.35]}
            scale={[1, 0.73, 1.51]}
          />
          <mesh
            name="Roundcube623"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube623.geometry}
            material={nodes.Roundcube623.material}
          />
        </mesh>
        <group name="Roundcube015" scale={0.11}>
          <mesh
            name="Roundcube015_1"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube015_1.geometry}
            material={nodes.Roundcube015_1.material}
          />
          <mesh
            name="Roundcube015_2"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube015_2.geometry}
            material={nodes.Roundcube015_2.material}
          />
        </group>
        <mesh
          name="Cube086"
          castShadow
          receiveShadow
          geometry={nodes.Cube086.geometry}
          material={nodes.Cube086.material}
          position={[-0.38, 9.82, -0.49]}
          rotation={[-0.68, 0.88, 0.56]}
          scale={[0.3, 0.23, 0.3]}
        >
          <mesh
            name="Cube006_1"
            castShadow
            receiveShadow
            geometry={nodes.Cube006_1.geometry}
            material={nodes.Cube006_1.material}
            position={[-0.64, 0.68, 0.02]}
          />
          <mesh
            name="Cube007"
            castShadow
            receiveShadow
            geometry={nodes.Cube007.geometry}
            material={nodes.Cube007.material}
            position={[0.31, -0.1, 2.84]}
            scale={[1.03, 1.17, 1.07]}
          />
          <mesh
            name="Cube008"
            castShadow
            receiveShadow
            geometry={nodes.Cube008.geometry}
            material={nodes.Cube008.material}
            position={[-0.08, -0.1, 0.11]}
            rotation={[0.03, 0.31, 0.26]}
            scale={[1.02, 0.99, 1]}
          />
          <mesh
            name="Cube009"
            castShadow
            receiveShadow
            geometry={nodes.Cube009.geometry}
            material={nodes.Cube009.material}
            position={[-1.2, -0.25, 2.5]}
          />
          <mesh
            name="Cube010"
            castShadow
            receiveShadow
            geometry={nodes.Cube010.geometry}
            material={nodes.Cube010.material}
            position={[-1.28, 0, 0]}
          />
          <mesh
            name="Sphere022"
            castShadow
            receiveShadow
            geometry={nodes.Sphere022.geometry}
            material={nodes.Sphere022.material}
            position={[-0.77, 0.42, 2.82]}
            rotation={[0.71, 1.13, -0.02]}
            scale={[0.21, 0.47, 0.2]}
          />
        </mesh>
        <group
          name="Roundcube002"
          position={[0, -0.22, 0.01]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.39}
        >
          <mesh
            name="Roundcube002_1"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube002_1.geometry}
            material={nodes.Roundcube002_1.material}
          />
          <mesh
            name="Roundcube002_2"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube002_2.geometry}
            material={materials["eyes.001"]}
          />
        </group>
        <mesh
          name="Roundcube005"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube005.geometry}
          material={nodes.Roundcube005.material}
          position={[0, -0.22, 0.01]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.39}
        />
        <mesh
          name="Roundcube008"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube008.geometry}
          material={nodes.Roundcube008.material}
          position={[0, -1.25, 0]}
          scale={0.19}
        />
        <mesh
          name="Roundcube353"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube353.geometry}
          material={nodes.Roundcube353.material}
          position={[-0.93, 3.05, 0]}
          rotation={[-0.82, 0, 0]}
          scale={0.12}
        >
          <mesh
            name="Cube213"
            castShadow
            receiveShadow
            geometry={nodes.Cube213.geometry}
            material={nodes.Cube213.material}
            position={[0, 0.69, 0.69]}
            rotation={[0.82, 0, 0]}
            scale={[1, 0.69, 1.56]}
          >
            <mesh
              name="Cone034"
              castShadow
              receiveShadow
              geometry={nodes.Cone034.geometry}
              material={nodes.Cone034.material}
              position={[0, 0.91, 1.27]}
              rotation={[3.12, 0, Math.PI]}
              scale={[-0.21, -0.49, -0.14]}
            />
            <mesh
              name="Cube214"
              castShadow
              receiveShadow
              geometry={nodes.Cube214.geometry}
              material={nodes.Cube214.material}
              position={[0, 58.28, 14.2]}
              rotation={[0.65, 0.1, 0]}
              scale={[1, 0.84, 1.58]}
            >
              <mesh
                name="Cone035"
                castShadow
                receiveShadow
                geometry={nodes.Cone035.geometry}
                material={nodes.Cone035.material}
                position={[0, 1.77, 1.23]}
                rotation={[-0.27, 0, 0]}
                scale={[0.21, 0.48, 0.15]}
              />
            </mesh>
            <mesh
              name="Cone036"
              castShadow
              receiveShadow
              geometry={nodes.Cone036.geometry}
              material={nodes.Cone036.material}
              position={[0, 2.85, 1.44]}
              rotation={[-2.56, 0, Math.PI]}
              scale={[0.46, 0.98, 0.42]}
            />
            <mesh
              name="Cylinder063"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder063.geometry}
              material={nodes.Cylinder063.material}
              position={[0, 0.76, 0.35]}
              rotation={[1.54, 0.02, 1.59]}
              scale={[0.47, 1.19, 1.06]}
            />
            <mesh
              name="Roundcube352"
              castShadow
              receiveShadow
              geometry={nodes.Roundcube352.geometry}
              material={nodes.Roundcube352.material}
              position={[0, 1.03, 0.79]}
              rotation={[-0.38, 0, 0]}
              scale={[0.38, 1.24, 0.29]}
            />
          </mesh>
          <mesh
            name="Roundcube354"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube354.geometry}
            material={nodes.Roundcube354.material}
            position={[0.58, -0.43, -0.18]}
            rotation={[0.79, 0, 0]}
          >
            <mesh
              name="Roundcube128"
              castShadow
              receiveShadow
              geometry={nodes.Roundcube128.geometry}
              material={nodes.Roundcube128.material}
              position={[0.54, -0.2, 0]}
              rotation={[-3.14, 0, Math.PI]}
              scale={[0.32, 0.32, 0.32]}
            />
          </mesh>
          <mesh
            name="Roundcube358"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube358.geometry}
            material={nodes.Roundcube358.material}
            position={[-0.58, -0.43, -0.18]}
            rotation={[-0.04, 0, 0]}
          >
            <mesh
              name="Roundcube129"
              castShadow
              receiveShadow
              geometry={nodes.Roundcube129.geometry}
              material={nodes.Roundcube129.material}
              position={[-0.54, -0.2, -0.01]}
              rotation={[-3.13, 0, Math.PI]}
              scale={[0.32, 0.32, 0.32]}
            />
          </mesh>
          <group
            name="Empty016"
            position={[-0.04, 0.78, -0.31]}
            rotation={[-0.03, -1.45, 0.22]}
            scale={[0.46, 0.46, 0.46]}
          >
            <mesh
              name="Cylinder096"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder096.geometry}
              material={nodes.Cylinder096.material}
              scale={[5.02, 5.02, 5.02]}
            />
          </group>
        </mesh>
        <mesh
          name="Roundcube431"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube431.geometry}
          material={nodes.Roundcube431.material}
          position={[-0.95, 2.06, 0]}
          rotation={[-0.66, -0.13, -0.09]}
          scale={[0.13, 0.12, 0.15]}
        >
          <mesh
            name="Cube257"
            castShadow
            receiveShadow
            geometry={nodes.Cube257.geometry}
            material={nodes.Cube257.material}
            position={[0, -0.14, 0]}
            rotation={[0.65, 0, 0]}
            scale={[0.35, 0.46, 0.43]}
          />
          <mesh
            name="Cylinder077"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder077.geometry}
            material={nodes.Cylinder077.material}
            position={[-0.14, 0.26, -0.4]}
            rotation={[-0.41, 0.02, -0.01]}
            scale={[0.83, 0.91, 0.72]}
          />
          <mesh
            name="Roundcube433"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube433.geometry}
            material={nodes.Roundcube433.material}
            position={[0, 0.94, 0.78]}
            rotation={[0.67, 0.23, -0.01]}
            scale={[1.05, 1.2, 1.14]}
          >
            <mesh
              name="Cylinder129"
              castShadow
              receiveShadow
              geometry={nodes.Cylinder129.geometry}
              material={nodes.Cylinder129.material}
              position={[0, 1.9, 1.05]}
              rotation={[0.61, 1.14, -0.58]}
              scale={[0.52, 0.52, 0.52]}
            />
            <mesh
              name="Roundcube435"
              castShadow
              receiveShadow
              geometry={nodes.Roundcube435.geometry}
              material={nodes.Roundcube435.material}
              position={[0, 0.28, 2.02]}
              scale={[0.21, 0.13, 0.11]}
            />
            <mesh
              name="Roundcube436"
              castShadow
              receiveShadow
              geometry={nodes.Roundcube436.geometry}
              material={nodes.Roundcube436.material}
              position={[0, 1.86, 0.78]}
              scale={[0.59, 1, 0.38]}
            />
            <mesh
              name="Roundcube459"
              castShadow
              receiveShadow
              geometry={nodes.Roundcube459.geometry}
              material={nodes.Roundcube459.material}
              position={[0, 0.58, 2.01]}
              scale={[0.2, 0.18, 0.18]}
            />
          </mesh>
          <group
            name="Armature109"
            position={[0.67, 0.59, 0.65]}
            rotation={[0.15, -1.24, 0.33]}
            scale={[-2.82, -3.51, -3.09]}
          >
            <primitive object={nodes.Bone_1} />
            <skinnedMesh
              name="Cube259"
              geometry={nodes.Cube259.geometry}
              material={nodes.Cube259.material}
              skeleton={nodes.Cube259.skeleton}
            />
          </group>
          <group
            name="Armature110"
            position={[-0.67, 0.66, 0.56]}
            rotation={[-2.99, -1.24, 0.33]}
            scale={[2.82, 3.51, 3.09]}
          >
            <primitive object={nodes.Bone_2} />
            <skinnedMesh
              name="Cube258"
              geometry={nodes.Cube258.geometry}
              material={nodes.Cube258.material}
              skeleton={nodes.Cube258.skeleton}
            />
          </group>
          <mesh
            name="Cylinder128"
            castShadow
            receiveShadow
            geometry={nodes.Cylinder128.geometry}
            material={nodes.Cylinder128.material}
            position={[0, 0.15, 0.87]}
            rotation={[0.54, 0, 0]}
            scale={[0.3, 0.16, 0.22]}
          />
        </mesh>
        <mesh
          name="Roundcube004"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube004.geometry}
          material={nodes.Roundcube004.material}
          position={[0, 1.05, 0]}
          scale={0.11}
        >
          <mesh
            name="Roundcube001"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube001.geometry}
            material={nodes.Roundcube001.material}
            position={[0, 2.4, 0]}
            scale={1.72}
          />
          <mesh
            name="Roundcube003"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube003.geometry}
            material={nodes.Roundcube003.material}
            position={[0, 2.35, 1.67]}
            rotation={[-0.08, 0, 0]}
            scale={[0.37, 0.67, 0.37]}
          />
          <mesh
            name="Roundcube006"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube006.geometry}
            material={nodes.Roundcube006.material}
            position={[0, -1.22, 0.35]}
            scale={[1, 0.73, 1.51]}
          />
          <mesh
            name="Roundcube007"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube007.geometry}
            material={nodes.Roundcube007.material}
          />
        </mesh>
        <mesh
          name="Cube001"
          castShadow
          receiveShadow
          geometry={nodes.Cube001.geometry}
          material={nodes.Cube001.material}
          position={[0, 1.21, 0.15]}
          rotation={[0.38, 0, 0]}
          scale={0.01}
        />
        <mesh
          name="Cube003"
          castShadow
          receiveShadow
          geometry={nodes.Cube003.geometry}
          material={nodes.Cube003.material}
          position={[0, 2.21, 0.04]}
          rotation={[0.19, 0, 0]}
          scale={0.14}
        />
        <mesh
          name="Roundcube011"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube011.geometry}
          material={nodes.Roundcube011.material}
          position={[0, 2.21, 0.04]}
          rotation={[0.19, 0, 0]}
          scale={[0.04, 0.02, 0.03]}
        />
        <mesh
          name="Cube004"
          castShadow
          receiveShadow
          geometry={nodes.Cube004.geometry}
          material={nodes.Cube004.material}
          position={[0, 2.21, 0.04]}
          rotation={[0.19, 0, 0]}
          scale={[0.2, 0.35, 0.07]}
        />
        <mesh
          name="Cylinder003"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={nodes.Cylinder003.material}
          position={[0, 2.21, 0.04]}
          rotation={[0.93, 1.19, -0.69]}
          scale={[0.1, 0.1, 0.09]}
        />
        <mesh
          name="Roundcube010"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube010.geometry}
          material={nodes.Roundcube010.material}
          position={[0, 2.21, 0.04]}
          rotation={[0.1, 0, 0]}
          scale={[0.05, 0.09, 0.05]}
        />
        <mesh
          name="Roundcube012"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube012.geometry}
          material={nodes.Roundcube012.material}
          position={[0, 2.1, 0]}
          rotation={[0.21, 0, 0]}
          scale={[0.11, 0.13, 0.11]}
        />
        <mesh
          name="Cube005"
          castShadow
          receiveShadow
          geometry={nodes.Cube005.geometry}
          material={nodes.Cube005.material}
          position={[0, 2.19, 0]}
          scale={[0.09, 0.04, 0.09]}
        />
        <mesh
          name="Cube011"
          castShadow
          receiveShadow
          geometry={nodes.Cube011.geometry}
          material={nodes.Cube011.material}
          position={[0, 2.07, 0]}
          scale={[0.05, 0.07, 0.07]}
        />
        <mesh
          name="Cylinder004"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={nodes.Cylinder004.material}
          position={[0.11, -0.48, -0.09]}
          rotation={[-1.05, -0.85, -0.95]}
          scale={[0.16, 0.16, 0.15]}
        />
        <mesh
          name="Cylinder007"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={nodes.Cylinder007.material}
          position={[0, 2.15, 0.1]}
          rotation={[-0.37, 0, 0]}
          scale={[0.04, 0.02, 0.03]}
        />
        <mesh
          name="Cylinder005"
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={nodes.Cylinder005.material}
          position={[0, 2.02, -0.04]}
          rotation={[-1.1, 0, 0]}
          scale={[0.15, 0.15, 0.14]}
        />
        <mesh
          name="Roundcube543"
          castShadow
          receiveShadow
          geometry={nodes.Roundcube543.geometry}
          material={nodes.Roundcube543.material}
          position={[0, 769.51, 1.29]}
          scale={[1, 0.85, 0.92]}
        >
          <mesh
            name="Roundcube549"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube549.geometry}
            material={nodes.Roundcube549.material}
            position={[0, 0.49, 0.5]}
            rotation={[0.47, 0, 0]}
            scale={[0.3, 0.17, 0.54]}
          />
          <mesh
            name="Cube332"
            castShadow
            receiveShadow
            geometry={nodes.Cube332.geometry}
            material={nodes.Cube332.material}
            position={[0, 0.56, 0.45]}
            rotation={[0.41, 0, 0]}
            scale={[0.04, 0.05, 0.05]}
          />
          <mesh
            name="Roundcube544_1"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube544_1.geometry}
            material={nodes.Roundcube544_1.material}
            position={[-0.7, 1.89, 0]}
            scale={[0.48, 0.57, 0.23]}
          />
          <mesh
            name="Roundcube545"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube545.geometry}
            material={nodes.Roundcube545.material}
            position={[0.61, 1.96, 0]}
            scale={[0.38, 0.45, 0.18]}
          />
          <mesh
            name="Roundcube546"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube546.geometry}
            material={nodes.Roundcube546.material}
            position={[-0.7, 1.89, 0.19]}
            scale={[0.26, 0.31, 0.04]}
          />
          <mesh
            name="Roundcube547"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube547.geometry}
            material={nodes.Roundcube547.material}
            position={[0.61, 1.95, 0.18]}
            scale={[0.16, 0.18, 0.04]}
          />
          <mesh
            name="Roundcube548"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube548.geometry}
            material={nodes.Roundcube548.material}
            position={[0, 0.02, -0.58]}
            scale={[1, 1.18, 1.37]}
          />
          <mesh
            name="Roundcube550"
            castShadow
            receiveShadow
            geometry={nodes.Roundcube550.geometry}
            material={nodes.Roundcube550.material}
            position={[0, 1.41, -0.58]}
            scale={[1, 1.18, 1.37]}
          />
        </mesh>
      </group>
    </group>
  );
}

useGLTF.preload("/3D_models/beasts/443815.glb");