// @ts-nocheck
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export default function Momo(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("/3D_models/beasts/443815.glb");
  console.log(materials);
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={0.11}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube015_1.geometry}
          material={materials.momo}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Roundcube015_2.geometry}
          material={materials.eyes}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/3D_models/beasts/443815.glb");